### ISSUE TITLE
.dll file isnt being noticed by ets2

### ISSUE THREAD

**Issue by dualznz** [nlhans/ets2-sdk-plugin#18]
Hi

I have written an application which works off this dll file BUT if other people add this .dll file which i have refrenced in my applicaiton, it is not noticed by the game so it does not load.

am i missing something.

The application is written in vb.net

app prefs

application installs to likes of C:\Program Files(x86)\appname
then copys the Ets2SdkClient.dll to Euro Truck Simulator 2\bin\win_86\plugins

but the warning does not come up in game, it does for me as im building the app

**Comment by nlhans** [comment]
Install to Euro Truck Simulator 2\bin\win_**x**86\plugins (with an x)?

**Comment by dualznz** [comment]
Hi cheers for the reply it still does it.

**Comment by dualznz** [comment]
Please note that i am refrencing the .dll into my application as a refrence, im thinking this could be the issue, how can i get it to work so then the lib can be in their game folder and the application not, i would easliy just refrence it to likes of c:\ but some people may also have thir game incalled on liked on E:\ and so forth.

do i have to refence it by a reg key or something?


cheers

**Comment by marcushann1** [comment]
I had this same problem with someone who was trying to use my app. I made a note that I had tried recompiling with different options (although I cannot remember which ones).

The error they were getting was: 0000007C or 7E

(Thinking about it, it MAY have been compiling in release rather than debug mode although I could be wrong)

I would suggest opening the console in game and checking for this error: http://trucksim.wikia.com/wiki/Console

**Comment by marcushann1** [comment]
Also, when you say as a reference, the way you are meant to use this is:

the .dll compiled from the c++ source goes into that folder (That is it)

you then use the dll created by the c# as a reference in your vb.net application and use that to get values (they communicate using a memory mapped file)

Your vb.net app should never reference the dll that is in the ets2 folder.

**Comment by dualznz** [comment]
hi

im not sure what u mean lol, i dont often work with .dll files im ny appz, and if i do they are always located in the app home dir, but because im using the .dll lib as a refrence im thinking the program thinks that the file dont exist for them.

so im trying to figure out how i can force the app to locate the .dll in the app.

i have built into the app on first launch for the users  to locate their ets2 directory so the .ddl can be sent over.

any thoughts.

im unterally stuck, i can get it going but no one else lol

**Comment by dualznz** [comment]
ok so it refrences it from my app folder?


but will theis cancel it from working, does it not need to be in the plugin/ dir for ets2 to to pick it up?

**Comment by marcushann1** [comment]
Yeah, I had the same problem of me being able to get it going but no-one else. If you look at the example c# app that is included with the source. You can see, that there are really three parts to this.

1. The dll that goes in the ets2 folder. This is the dll you download from the releases page. The c++ source for this is based on that given to us by SCS
2. The c# code that reads the Memory Mapped File which is a project called: Ets2SdkClient. This compiles down to a (different) dll file THIS is the one you need to reference in your vb
3. There is an example c# app which references the Ets2SdkClient dll file and displays values from the game.

Marcus.

**Comment by marcushann1** [comment]
However, the fact that you say it works for you, suggests that this isn't the issue. And that it is probably something else as if you had done that bit wrong it wouldn't work for you either.

I would suggest asking them to:

"

If not, could you open the console using the steps outlined here: http://trucksim.wikia.com/wiki/Console and look for a line that looks something like this:

00:00:04.889 : loading 'telemetry' 'D:/Games/Steam/steamapps/common/Euro Truck Simulator 2/bin/win_x86/plugins/telemetry.dll'

and tell me what the next line says?

"

And posting that here so that we can better identify the issue.

**Comment by dualznz** [comment]
ok ill try that.

ive just done a test and i removed the .dll from the plugins folder and only had mine in my folder and it seems to be working strange

**Comment by marcushann1** [comment]
Also,

Make sure that they have vc++ installed if it is the same error as above as this is another common cause of that error.

I do not remember what version this repo uses as I build my own but if you want I'm happy to give you a copy of mine (which is built using vc++ 2013) so they need: https://www.microsoft.com/en-GB/download/details.aspx?id=40784

**Comment by dualznz** [comment]
ahh ok cheers for all that, ive just installed ets2 on my test bench and thats a brand new blank windows 7 of, so in theory it will be as if it was anyone else so i can try all of this makes it easier when i dont have to wait for testers to come online lol
