### ISSUE TITLE
JobFinished Event Not Fired when Level Up

### ISSUE THREAD

**Issue by jammerxd** [nlhans/ets2-sdk-plugin#22]
Hello,
I have found a bug where the job data is not reset after a profile upgrade/level up. The OnJob stays true and the JobFinished stays false and everything indicates that the hob is still in progress, even the trailerattached is still true. This testing was done in the quick job/not owning my own truck on a new profile. Can you fix this?

**Comment by nlhans** [comment]
The onJob flag is reset once the trailerAttached value goes low. See https://github.com/nlhans/ets2-sdk-plugin/blob/master/ets2-telemetry/src/ets2-telemetry.cpp#L95

The trailer attached flag, as you indicated stuck high, is directly from ETS2 SDK: https://github.com/nlhans/ets2-sdk-plugin/blob/master/ets2-telemetry/src/ets2-telemetry.cpp#L382

This indicates a minor bug in ETS2 causing the failure of the "onJob" flag. Either because of indeed the level-up screen, or because of the quick job (I haven't done a quick job in ages).

Unfortunately I don't have got any other information to go by that the job has been completed, so I can't easily think of a fix.
