### ISSUE TITLE
Can't debug telemtry in x64

### ISSUE THREAD

**Issue by danielalmeida1481** [nlhans/ets2-sdk-plugin#49]
I made some changes in the telemetry and I wanted to use the new version in x64 but I can't debug it in x64.

**Comment by RenCloud** [comment]
This project use a function to convert the byte array from the shared memory to an c# object. Sadly, because 32 bit and 64 bit use different size for handling arrays etc., this convert function create errors. 

I doesn't work with this function, but some research about it create 2 ways that may are possible to fix it

1.  use `fixed` and unsafe code. I don't want to use this and also I didn't get it to work 
so I choose
1.  make the conversion by hand. That works very well. I actually work on that in my fork in a dev branch if you're still interested. Overall the code should be shorter with this version as befour and more modifiable

may it is also possible to fix the error the function creates, but I try it for a few hours + research and it doesn't worked after that.
