### ISSUE TITLE
Truck manufacturer/model

### ISSUE THREAD

**Issue by JustinRR** [nlhans/ets2-sdk-plugin#8]
Hey,

Not sure why, but while learning what to use by your example, I noticed that the truck make/model does not work. Only the ID does, which displays it as (vehicle.volvo.fh_2012) or something similar.

Is there a reason why? Any help would be great.

Also, do you know why once you complete a job, the job data doesn't clear from the telemetry unless you restart ETS2?

Thanks for your awesome plugin. It's about to make my VTC even more amazing!

**Comment by yodek** [comment]
I use plugin what is with Funbit's Telemetry WebServer and work fine.

.truckMake & .truckModel

**Comment by JustinRR** [comment]
I'm not using funbits. I'm using this one.

**Comment by nlhans** [comment]
There are 2 truck and manufacturer field's; one is ID and one is the "human readable" format.

Both should be in the API. If your application talks C#, you can look up how those fields are derived here:
https://github.com/nlhans/ets2-sdk-plugin/blob/master/ets2-client/C%23/Ets2SdkClient/Ets2Telemetry.cs#L181
https://github.com/nlhans/ets2-sdk-plugin/blob/master/ets2-client/C%23/Ets2SdkClient/Ets2SdkTelemetry.cs#L80

The inconsistency in fields were because of backwards compatibility (older plugins did not report the human readable format) and change in ways how strings were stored.

I am aware of the job information not updating when finished. For a short-term work around I recommended looking at the trailer attached flag to override job info, but I will need to research if SCS SDK provides an event on job completion.

**Comment by JustinRR** [comment]
Thanks! I'll have to test that out. 

Also, I did use that trailer work around for now server side to mask the job data.

**Comment by JustinRR** [comment]
Hey, so I checked it out, and made sure I was using everything correctly....

Even in your demo that is available for download, it still does not show the truck info. Attached is a screenshot. As you can see by that, Truck and Manufacturer do not output anything except for (TruckId)



Please let me know what I can do to fix this.

Thanks!
![demo](https://cloud.githubusercontent.com/assets/9011983/6932461/1fbc0a5e-d7df-11e4-9896-7a0f968639b8.png)

**Comment by nlhans** [comment]
Looking again at your screenshot dump, you are running an old SDK DLL.

The C# application is included with the 1.2 release. It is updated for each version of the plugin; so it should be accompied with the same DLL.
Otherwise it may appear like new added fields are empty.

**Comment by JustinRR** [comment]
Oh gotcha. Well, with the newest update today, everything is working perfectly and I was able to update my application, thank you very much!
